// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnNsHydl3_r_ME3mpKhmwnUd1zbAsSJ7o',
    appId: '1:277481522419:web:8e57f657ad63bd2e426386',
    messagingSenderId: '277481522419',
    projectId: 'rns-healthcare',
    authDomain: 'rns-healthcare.firebaseapp.com',
    storageBucket: 'rns-healthcare.firebasestorage.app',
    measurementId: 'G-57XKSZ7LJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABj4J7zZIyNNV78hOJ_pQqh0P71L649M8',
    appId: '1:277481522419:android:4962e71965765d08426386',
    messagingSenderId: '277481522419',
    projectId: 'rns-healthcare',
    storageBucket: 'rns-healthcare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0AAZsGqZuoDOVTwQ2hKv91MxMXZDZW-Y',
    appId: '1:277481522419:ios:45cd722932739905426386',
    messagingSenderId: '277481522419',
    projectId: 'rns-healthcare',
    storageBucket: 'rns-healthcare.firebasestorage.app',
    iosBundleId: 'com.example.clinicWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0AAZsGqZuoDOVTwQ2hKv91MxMXZDZW-Y',
    appId: '1:277481522419:ios:45cd722932739905426386',
    messagingSenderId: '277481522419',
    projectId: 'rns-healthcare',
    storageBucket: 'rns-healthcare.firebasestorage.app',
    iosBundleId: 'com.example.clinicWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnNsHydl3_r_ME3mpKhmwnUd1zbAsSJ7o',
    appId: '1:277481522419:web:52995d567419671c426386',
    messagingSenderId: '277481522419',
    projectId: 'rns-healthcare',
    authDomain: 'rns-healthcare.firebaseapp.com',
    storageBucket: 'rns-healthcare.firebasestorage.app',
    measurementId: 'G-LW043MVR9T',
  );
}
